In [1]:
import numpy as np
Array=[1,2,3,4]
print(Array)
type(Array)

[1, 2, 3, 4]


list

In [31]:
import numpy as np
Array=np.array([[1,2,3,4],[7,8,9,0]])
type(Array)
Array.shape


(2, 4)

In [65]:
import numpy as np
Arr = np.arange(20)  
print(Arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
import numpy as np

Array = np.array([1, 2, 3,4])
Array.shape

(4,)

In [61]:
import numpy as np
Arr = np.arange(21).reshape(7,3)  # Corrected the function name from np.arrange to np.arange
print(Arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [67]:
import numpy as np
Arr = np.arange(24).reshape(2,12)
print(Arr)
Arr=np.arange(24).reshape(3,8)
print(Arr)
Arr=np.arange(24).reshape(4,6)
print(Arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
